import { WorkoutTemplate, WorkoutPlanType } from './types';

export const WORKOUT_TEMPLATES: Record<WorkoutPlanType, WorkoutTemplate> = {
  'chest-triceps': {
    id: 'chest-triceps',
    name: 'Chest + Triceps',
    workoutType: 'chest-triceps',
    estimatedDuration: 70,
    estimatedCaloriesMin: 300,
    estimatedCaloriesMax: 400,
    description: 'Push day focusing on chest and triceps',
    exercises: [
      {
        name: 'Bench Press',
        targetSets: 4,
        targetRepsMin: 4,
        targetRepsMax: 10,
        category: 'chest',
      },
      {
        name: 'Incline DB Press',
        targetSets: 3,
        targetRepsMin: 6,
        targetRepsMax: 12,
        category: 'chest',
      },
      {
        name: 'Cable Chest Press',
        targetSets: 3,
        targetRepsMin: 10,
        targetRepsMax: 12,
        category: 'chest',
      },
      {
        name: 'DB Fly',
        targetSets: 3,
        targetRepsMin: 12,
        targetRepsMax: 15,
        category: 'chest',
      },
      {
        name: 'Rope Pushdown',
        targetSets: 3,
        targetRepsMin: 10,
        targetRepsMax: 12,
        category: 'triceps',
      },
      {
        name: 'Overhead Extension',
        targetSets: 3,
        targetRepsMin: 8,
        targetRepsMax: 12,
        category: 'triceps',
      },
      {
        name: 'Skull Crushers',
        targetSets: 3,
        targetRepsMin: 8,
        targetRepsMax: 10,
        category: 'triceps',
      },
    ],
  },
  'back-biceps': {
    id: 'back-biceps',
    name: 'Back + Biceps',
    workoutType: 'back-biceps',
    estimatedDuration: 70,
    estimatedCaloriesMin: 300,
    estimatedCaloriesMax: 400,
    description: 'Pull day focusing on back and biceps',
    exercises: [
      {
        name: 'Lat Pulldown',
        targetSets: 3,
        targetRepsMin: 8,
        targetRepsMax: 12,
        category: 'back',
      },
      {
        name: 'Seated Cable Row',
        targetSets: 3,
        targetRepsMin: 6,
        targetRepsMax: 12,
        category: 'back',
      },
      {
        name: 'DB Row',
        targetSets: 3,
        targetRepsMin: 8,
        targetRepsMax: 12,
        category: 'back',
      },
      {
        name: 'Rear Delt Cable',
        targetSets: 3,
        targetRepsMin: 12,
        targetRepsMax: 15,
        category: 'back',
      },
      {
        name: 'EZ Bar Curl',
        targetSets: 3,
        targetRepsMin: 6,
        targetRepsMax: 12,
        category: 'biceps',
      },
      {
        name: 'Incline DB Curl',
        targetSets: 3,
        targetRepsMin: 8,
        targetRepsMax: 12,
        category: 'biceps',
      },
      {
        name: 'Preacher Curl',
        targetSets: 3,
        targetRepsMin: 10,
        targetRepsMax: 12,
        category: 'biceps',
      },
    ],
  },
  'swimming-core': {
    id: 'swimming-core',
    name: 'Swimming + Core',
    workoutType: 'swimming-core',
    estimatedDuration: 50,
    estimatedCaloriesMin: 300,
    estimatedCaloriesMax: 350,
    description: 'Cardio swimming session with core work',
    exercises: [
      {
        name: 'Swimming',
        targetSets: 1,
        targetRepsMin: 30,
        targetRepsMax: 45,
        category: 'cardio',
      },
      {
        name: 'Hanging Leg Raises',
        targetSets: 3,
        targetRepsMin: 12,
        targetRepsMax: 15,
        category: 'core',
      },
      {
        name: 'Plank',
        targetSets: 3,
        targetRepsMin: 30,
        targetRepsMax: 60,
        category: 'core',
      },
      {
        name: 'Mobility Work',
        targetSets: 1,
        targetRepsMin: 10,
        targetRepsMax: 15,
        category: 'mobility',
      },
    ],
  },
  'legs-shoulders': {
    id: 'legs-shoulders',
    name: 'Legs + Shoulders',
    workoutType: 'legs-shoulders',
    estimatedDuration: 80,
    estimatedCaloriesMin: 400,
    estimatedCaloriesMax: 500,
    description: 'Leg day with shoulder work',
    exercises: [
      {
        name: 'Squat',
        targetSets: 4,
        targetRepsMin: 4,
        targetRepsMax: 10,
        category: 'legs',
      },
      {
        name: 'Leg Press',
        targetSets: 3,
        targetRepsMin: 10,
        targetRepsMax: 15,
        category: 'legs',
      },
      {
        name: 'Leg Extension',
        targetSets: 3,
        targetRepsMin: 12,
        targetRepsMax: 15,
        category: 'legs',
      },
      {
        name: 'Hamstring Curl',
        targetSets: 3,
        targetRepsMin: 10,
        targetRepsMax: 12,
        category: 'legs',
      },
      {
        name: 'RDL (Optional)',
        targetSets: 3,
        targetRepsMin: 8,
        targetRepsMax: 10,
        category: 'legs',
      },
      {
        name: 'Overhead Press',
        targetSets: 3,
        targetRepsMin: 6,
        targetRepsMax: 12,
        category: 'shoulders',
      },
      {
        name: 'Lateral Raise',
        targetSets: 4,
        targetRepsMin: 12,
        targetRepsMax: 15,
        category: 'shoulders',
      },
    ],
  },
  'swimming-light': {
    id: 'swimming-light',
    name: 'Swimming + Light Pump',
    workoutType: 'swimming-light',
    estimatedDuration: 50,
    estimatedCaloriesMin: 300,
    estimatedCaloriesMax: 350,
    description: 'Recovery day with swimming and light work',
    exercises: [
      {
        name: 'Swimming',
        targetSets: 1,
        targetRepsMin: 30,
        targetRepsMax: 45,
        category: 'cardio',
      },
      {
        name: 'Light Arms/Shoulders',
        targetSets: 3,
        targetRepsMin: 12,
        targetRepsMax: 15,
        category: 'arms',
      },
      {
        name: 'Mobility Work',
        targetSets: 1,
        targetRepsMin: 10,
        targetRepsMax: 15,
        category: 'mobility',
      },
    ],
  },
  'plyo-sprints': {
    id: 'plyo-sprints',
    name: 'Plyometrics + Sprints',
    workoutType: 'plyo-sprints',
    estimatedDuration: 50,
    estimatedCaloriesMin: 350,
    estimatedCaloriesMax: 500,
    description: 'Explosive power and speed work',
    exercises: [
      {
        name: 'Box Jumps',
        targetSets: 3,
        targetRepsMin: 5,
        targetRepsMax: 5,
        category: 'plyo',
      },
      {
        name: 'Broad Jumps',
        targetSets: 3,
        targetRepsMin: 5,
        targetRepsMax: 5,
        category: 'plyo',
      },
      {
        name: 'Jump Squats',
        targetSets: 3,
        targetRepsMin: 6,
        targetRepsMax: 6,
        category: 'plyo',
      },
      {
        name: 'Sprints 30m',
        targetSets: 8,
        targetRepsMin: 1,
        targetRepsMax: 1,
        category: 'sprints',
      },
      {
        name: 'Sprints 60m',
        targetSets: 5,
        targetRepsMin: 1,
        targetRepsMax: 1,
        category: 'sprints',
      },
    ],
  },
  'rest': {
    id: 'rest',
    name: 'Rest / Recovery',
    workoutType: 'rest',
    estimatedDuration: 30,
    estimatedCaloriesMin: 50,
    estimatedCaloriesMax: 150,
    description: 'Active recovery and mobility',
    exercises: [
      {
        name: 'Walk / Light Jog',
        targetSets: 1,
        targetRepsMin: 20,
        targetRepsMax: 30,
        category: 'cardio',
      },
      {
        name: 'Stretching',
        targetSets: 1,
        targetRepsMin: 15,
        targetRepsMax: 20,
        category: 'mobility',
      },
    ],
  },
  'custom': {
    id: 'custom',
    name: 'Custom Workout',
    workoutType: 'custom',
    estimatedDuration: 60,
    estimatedCaloriesMin: 200,
    estimatedCaloriesMax: 400,
    description: 'Create your own workout',
    exercises: [],
  },
};

export const DEFAULT_WEEKLY_PLAN = {
  monday: 'chest-triceps' as WorkoutPlanType,
  tuesday: 'back-biceps' as WorkoutPlanType,
  wednesday: 'swimming-core' as WorkoutPlanType,
  thursday: 'legs-shoulders' as WorkoutPlanType,
  friday: 'swimming-light' as WorkoutPlanType,
  saturday: 'plyo-sprints' as WorkoutPlanType,
  sunday: 'rest' as WorkoutPlanType,
};

export function getWorkoutForDay(dayOfWeek: number): WorkoutPlanType {
  const days = ['sunday', 'monday', 'tuesday', 'wednesday', 'thursday', 'friday', 'saturday'];
  const dayName = days[dayOfWeek] as keyof typeof DEFAULT_WEEKLY_PLAN;
  return DEFAULT_WEEKLY_PLAN[dayName];
}

export function getDayName(dayOfWeek: number): string {
  const days = ['Sunday', 'Monday', 'Tuesday', 'Wednesday', 'Thursday', 'Friday', 'Saturday'];
  return days[dayOfWeek];
}
